### ISSUE TITLE
Rewrite To-Do

### ISSUE THREAD

**Issue by splatterxl** [fuwa-org/fuwa#50]
# To-do

# Gateway
- [ ] Shards
  - [x] Get info from `/gateway/bot`
  - [x] Get sharding info from environment? Would need a sharding manager.
  - [x] Handle heartbeats
  - [x] Identify and resume
  - [ ] Handle messages
    - [x] `HELLO`
    - [x] `READY`
    - [x] `GUILD_CREATE`
      - [x] Await known guilds at startup and don't emit `ready` event without them
      - [x] Warn without `GUILDS` intent
      - [x] Emit `guildCreate` if new guild
    - [x] `RECONNECT`
    - [x] `MESSAGE_*`
    - [x] `GUILD_MEMBER_*`
    - [ ] `CHANNEL_*`
    - [ ] `INTEGRATION_*`
  - [x] Be able to resume if required
- [ ] Sharding Manager? (in progress)

# Guilds
Guilds are the core of Discord. Here's what we need to support in Fuwa:

- [x] Approximate counts
- [x] Counts
- [x] Max counts
- [x] Vanity URLs
- [ ] Presences
- [x] Members
  - [x] Create members
    - [x] Handle user-member links
  - [x] Member manager
    - [x] `GuildMemberManager.prototype.add(id: Snowflake)` (possibly also add a param for a bearer token?)
- [ ] #65

# Presences

- [ ] Cache
- [ ] Self
  - [ ] Set self status (dnd, idle, invisible)
  - [ ] Self self presence

# Channels 

- [x] Voice Channels
  - [x] Voice in Text
- [x] <s>Store Channels</s> N/A
- [x] Text Channels
  - [x] Messages
    - [x] Cache
    - [ ] Handle replies
    - [x] Sending messages
  - [x] <s>News channels</s> 
  - [x] Text-in-Voice 
- [x] Voice channels
  - [x] <s>Stage channels</s>
- [x] #58 
- [x] Editing channels
- [x] Deleting channels
- [ ] Permissions - tracked in #65

**Comment by splatterxl** [comment]
This issue is actually obsoleted by #62
