### ISSUE TITLE
feat: sharding

### ISSUE THREAD

**Issue by splatterxl** [fuwa-org/fuwa#60]
# To-do
- [x] Sharding manager
- [x] WebSocket manager that handles shard sockets
- [x] Get shard for guild 
- [ ] Broadcast evaluations between managers
